apiVersion: v1
kind: Secret
metadata:
  name: rhacs-prometheus-additional-scrape-configs
  namespace: tssc-acs
stringData:
  prometheus-additional.yaml: |
    - job_name: 'rhacs-metrics'
      scheme: https
      metrics_path: /metrics
      bearer_token_file: /var/run/secrets/tokens/token
      tls_config:
        insecure_skip_verify: true
      static_configs:
      - targets: ['central.tssc-acs.svc.cluster.local:443']
