apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  name: rhacs-scrape-config
  namespace: tssc-acs
  labels:
    app: central
spec:
  jobName: rhacs-metrics
  scheme: HTTPS
  staticConfigs:
    - targets:
        - "central.tssc-acs.svc.cluster:443"
  tlsConfig:
    ca:
      secret:
        key: ca.pem
        name: service-ca
    cert:
      secret:
        key: tls.crt
        name: rhacs-prometheus-tls
    keySecret:
      key: tls.key
      name: rhacs-prometheus-tls
